# Global defaults
paste: false          # typewrite expansions instead of clipboard paste
key_delay: 2          # smooth typing

# Only use clipboard paste where necessary (e.g., Emacs), with a safer key
# global_vars:
#   - name: APP_IS_EMACS
#     type: shell
#     params: { cmd: 'echo "$ESPANSO_APP_NAME" | grep -iq emacs && echo 1 || echo 0' }

matches:
  - trigger: ":sig"
    replace: "— your expansion —"
    # For Emacs, switch to clipboard paste with Shift+Insert + delay
    vars: [{name: APP_IS_EMACS}]
    conditions: ["var.APP_IS_EMACS == 1"]
    use_clipboard: true
    propagate_case: false

# Clipboard paste behavior (only used when use_clipboard: true)
# paste_shortcut: "SHIFT+INSERT"
# paste_delay: 120
# restore_clipboard: true
